version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
      - "6000:6000"
    depends_on:
      - postgres
    environment:
      PORT: 6000
      AM1T: amit
      SUMIT: sample
      YUIE: sniriccm
      DATABASE_URL: postgres://todoapp@postgres/todos