version: '2'
services:
  web:
    image: vaishanvi1234/samp11:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTURL: 127.0.0.1:5001
      SERVICE: app1
      PORT: 5000
      AMIT: hello/amit/sumit/vikas